language: dart
os: windows
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=C:\src\flutter\bin:$PATH

cache:
  directories:
    - $HOME/.pub-cache